### ISSUE TITLE
How to set number of toast on screen ?

### ISSUE THREAD

**Issue by Mukthayar1** [alielmajdaoui/react-native-gtoast#2]
how can i set to show only one toast at a time ?
<img width="280" alt="Screenshot 2022-05-01 at 12 53 49 AM" src="https://user-images.githubusercontent.com/64356624/166120702-b7ba07a4-91df-4eeb-97dd-c52354922218.png">

@alielmajdaoui @retyui

**Comment by retyui** [comment]
why are you tagged me?

**Comment by Mukthayar1** [comment]
> why are you tagged me?
You are not contributor ?

**Comment by retyui** [comment]
I am a contributor, but not a maintainer

**Comment by alielmajdaoui** [comment]
If you set an id for the toast, it will be shown once until it disappear.

https://github.com/alielmajdaoui/react-native-gtoast#unique-toasts

**Comment by alielmajdaoui** [comment]
Closing for no feedback.
